; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30705.0 

	TITLE	D:\Tyler\Documents\learn\reverse-engineering\re4b\returning values\1-4.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f	PROC
; File D:\Tyler\Documents\learn\reverse-engineering\re4b\returning values\1-4.c
; Line 1
	push	ebp ; Saves base pointer on stack
	mov	ebp, esp ; Places stack pointer into base register
; Line 2
	mov	eax, 123 ; Moves immediate value 123 into %eax for return
; Line 3
	pop	ebp ; Restores base pointer from stack
	ret	0 ; Returns from function
_f	ENDP
_TEXT	ENDS
END
