; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30705.0 

	TITLE	D:\Tyler\Documents\learn\reverse-engineering\re4b\an empty function\1-3.obj
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMT
INCLUDELIB OLDNAMES

PUBLIC	_f
; Function compile flags: /Odtp
_TEXT	SEGMENT
_f	PROC
; File D:\Tyler\Documents\learn\reverse-engineering\re4b\an empty function\1-3.c
; Line 1
	push	ebp
	mov	ebp, esp
; Line 3
	pop	ebp
	ret	0
_f	ENDP
_TEXT	ENDS
END
